Dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

tugas1PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin 
import update_status.urls as update_status
import halaman_profile.urls as halaman_profile
import add_friend.urls as add_friend
import Dashboard.urls as Dashboard
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^halaman-profile/', include(halaman_profile, namespace='halaman-profile')),
    url(r'^add-friend/', include(add_friend, namespace='add-friend')),
    url(r'^Dashboard/', include(Dashboard, namespace='Dashboard')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent = True)),

]

templates/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p>&copy; Kelompok 13 - PPW B</p>

templates/partials/header.html
<nav class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'update-status:index' %}">Coffee Break</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav" style="float: right;">
        <!-- LINK MENUJU Status, Profile, Friends, stats -->
        <li><a href="{% url 'update-status:index' %}">Status</a></li>
        <li><a href="{% url 'halaman-profile:index' %}">Profile</a></li>
        <li><a href="{% url 'add-friend:index' %}">Friends</a></li>
        <li><a href="{% url 'Dashboard:index' %}">Stats</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>