Dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

add_friend/urls.py
from django.conf.urls import url
from .views import index, add

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add', add, name='add')
]

tugas1PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin 
import update_status.urls as update_status
import halaman_profile.urls as halaman_profile
import add_friend.urls as add_friend
import Dashboard.urls as Dashboard
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^halaman-profile/', include(halaman_profile, namespace='halaman-profile')),
    url(r'^add-friend/', include(add_friend, namespace='add-friend')),
    url(r'^Dashboard/', include(Dashboard, namespace='Dashboard')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent = True)),

]

add_friend/models.py
from django.db import models

# Create your models here.
class AddFriend(models.Model):
    name = models.CharField(max_length=27)
    url = models.URLField(max_length=100)
    created_date = models.DateTimeField(auto_now_add=True)

add_friend/forms.py
from django import forms

class AddFriend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi!',
    }
    name_attributes = {
        'type' : 'text',
	'class' : 'name_input_form_text_area',
        'rows' : 4,
	'cols' : 100,
	'placeholder' : "Isi dengan nama teman anda...",
    }
    url_attributes = {
	'type' : 'text',
	'class' : 'url_input_form_text_area',
	'rows' : 4,
	'cols' : 100,
	'placeholder' : "Isi dengan url teman anda...",
	}

    name = forms.CharField(label='Name ',required=True,max_length=30,widget=forms.TextInput(attrs=name_attributes))
    url  = forms.URLField(label='URLs ',required=True,max_length=100,widget=forms.URLInput(attrs=url_attributes))
    

add_friend/views.py
from django.shortcuts import render
from .models import AddFriend
from .forms import AddFriend_Form
from django.http import HttpResponseRedirect
# Create your views here.
response = {}
def index(request):
    response['author'] = "Intan Wulandari"
    addfriend = AddFriend.objects.all()
    response['addfriend'] = addfriend
    html = 'add_friend/add_friend.html'
    response['addfriend_form'] = AddFriend_Form
    return render(request, html, response)


def add(request):
    form = AddFriend_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
	    response['name'] = request.POST['name']
	    response['url'] = request.POST['url']
	    friend = AddFriend(name = response['name'],url = response['url'])
	    friend.save()
	    return HttpResponseRedirect('/add-friend/')
    else:
	    return HttpResponseRedirect('/add-friend/')

add_friend/templates/add_friend/add_friend.html
{% extends "layout/base.html" %}
{% block content %}
{% load staticfiles %}
<section name="input-friend" id="input-friend">
    <div class="container">
        <form id="form" method="POST" action="{% url 'add-friend:add' %}">
            <h1 class="title-form">Add Friend</h1>
            {% csrf_token %}
            {{ addfriend_form }}
            <p></p>
            <button id="submit" type="submit" class="btn btn-lg default" style="right">Submit</button>
            <br/>
        </form>
    </div>
</section>
<section name="friend-list" id="friend-list">
    <div class="container">
        <h1 class="title-list">List Friend</h1>
        <table class="tabel">
            {% if addfriend %}
                {% for i in addfriend %}
                    <tbody>
                        <tr>
                            <td class="add-name">{{i.name}}</td>
                            <td class="add-url"><a href="{{i.url}}"><center>{{i.url}}</center></a></td>
                            <td class="add-date">Added {{i.created_date}}</td>
                        </tr>
                    </tbody>
                    {% endfor %}
                {% else %}
                <div class="alert alert-danger text-center">
                    <strong>Maaf!</strong> Anda Belum Memiliki Teman
                </div>
                {% endif %}
        </table>
    </div>
</section>
{% endblock %}