Dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

tugas1PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin 
import update_status.urls as update_status
import halaman_profile.urls as halaman_profile
import add_friend.urls as add_friend
import Dashboard.urls as Dashboard
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^halaman-profile/', include(halaman_profile, namespace='halaman-profile')),
    url(r'^add-friend/', include(add_friend, namespace='add-friend')),
    url(r'^Dashboard/', include(Dashboard, namespace='Dashboard')),
    url(r'^$', RedirectView.as_view(url='/update-status/', permanent = True)),

]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_status


urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_status', add_status, name='add_status'),
]

update_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	status = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

update_status/forms.py
from django import forms

class Update_Status_Form(forms.Form):
	error_message = {
		'required': 'Have nothing to post?',
	}
	update_status_attrs = {
		'type': 'text',
		'cols': 165,
		'rows': 4,
		'class': 'update-status-form-textarea',
		'placeholder': "Write your day here!"
	}

	status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=update_status_attrs))

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Update_Status_Form
from .models import Status

# Create your views here.
response = {}
def index(request):
	response['author'] = "Mohammad Ahnaf Zain Ilham"
	status = Status.objects.all()
	response['status'] = status
	html = 'update_status/update_status.html'
	response['update_status_form'] = Update_Status_Form
	return render(request, html, response)

def add_status(request):
	form = Update_Status_Form(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		status = Status(status=response['status'])
		status.save()
		return HttpResponseRedirect('/update-status/')
	else:
		return HttpResponseRedirect('/update-status/')

update_status/templates/update_status/update_status.html
{% extends "layout/base.html" %}

{% block content %}
{% load staticfiles %}
<section name="input-update-status" id="input-update-status">
	<div class="container" align="center">
		<form id="form", method="POST", action="{% url 'update-status:add_status' %}">
			<h1><b>Update Status</b></h1>
			{% csrf_token %}
			{{ update_status_form }}
			<input id="post", type="submit", class="btn btn-default", value="Post", style="float:right">
			<br>
		</form>
	</div>
</section>
<section name="all-status" id="all-status">
	<div class="container" align="center">
		<div class="flex">
			{% if status %} 			
				{% for data in status reversed %}
					<div>
						<div class="show-status" align="left">
							<div class="profile">
								<h4>
								<img id="icon" src="{%static 'icon.png' %}">
								<b>Zain Ilham</b>
								</h4>
							</div>
							<div class="status-content">
								<pre>{{data.status|linebreaksbr}}</pre>
							</div>
							<div class="status-date-added">
								{{data.created_date}}
							</div>
						</div>
					</div>
				{% endfor %}
			{% else %}
			<div class="alert alert-danger text-center">
				<strong>No status added.</strong> Add your status now!
			</div>
			{% endif %}
		</div>
	</div>
</section>


{% endblock %}											 				